# The theme to use
remote_theme: just-the-docs/just-the-docs

# The title and description of your site
title: A Practical Learning Path for SOC Analysts
description: A series of guides for aspiring cybersecurity and SOC analysts.

# The URL and baseurl for your site, critical for GitHub Pages
url: "https://terjeru.github.io"
baseurl: "/SOC-Analyst-Learning-Path"

# Enable search
search_enabled: true
