# The theme to use
remote_theme: just-the-docs/just-the-docs

# The title and description of your site
title: A Practical Learning Path for SOC Analysts
description: A series of guides for aspiring cybersecurity and SOC analysts.

# The URL and baseurl for your site, critical for GitHub Pages
url: "https://terjeru.github.io"
baseurl: "/SOC-Analyst-Learning-Path"

# Enable search
search_enabled: true

# Just the Docs theme specific settings
aux_links:
  "SOC Analyst Learning Path on GitHub":
    - "https://github.com/TerjeRu/SOC-Analyst-Learning-Path"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer content
footer_content: "This project is licensed under the MIT License."

# Color scheme (optional)
color_scheme: nil

# Google Analytics (optional)
# ga_tracking: UA-XXXXXXXX-X

# Plugins (GitHub Pages supported)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
