# Site settings
title: A Practical Learning Path for SOC Analysts
description: >- # this means to ignore newlines until "baseurl:"
  A series of guides for aspiring cybersecurity and SOC analysts,
  moving from fundamentals to advanced concepts.

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
